CC=gcc
CFLAGS=-o
LDFLAGS=-lgsl -lgslcblas
GNUWIN32="C:\Documents and Settings\Kevin1\Desktop\GnuWin32"
FLAGS=-I"$(GNUWIN32)/include" -L"$(GNUWIN32)/lib"
SOURCES=main.c
EXECUTABLE=conics_quadrics_classifier

all:
	$(CC) $(LDFLAGS) $(FLAGS) $(SOURCES) $(CFLAGS) $(EXECUTABLE)
